# This workflow will build and test a Java project with Maven

name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  dupe_check:
    name: Check for Duplicate Workflow Run
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          concurrent_skipping: same_content_newer
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build:
    name : Build & Test
    needs:
      - dupe_check
    if: needs.dupe_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Setup JDK 17
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: zulu
          java-version: 17
          cache: maven
      - name: Build and run Tests
        run: mvn clean verify -s maven/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Test Results
          path: |
            **/target/failsafe-reports/*.xml
            **/target/surefire-reports/*.xml
      - name: Publish Unit Test Results
        if: ${{ !cancelled() && (github.actor != 'dependabot[bot]' || (github.event_name == 'push' && !contains(github.ref, 'dependabot'))) }}
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        continue-on-error: true
        with:
          fail_on: nothing
          files: |
            **/target/failsafe-reports/*.xml
            !**/target/failsafe-reports/failsafe-summary.xml
            **/target/surefire-reports/*.xml
